### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by noringname** [WaterScenes/WaterScenes#1]
Hi, very nice work! Will you release your early fusion yolov8, yolox, Achelous works? That will be a great starting point for further research.

**Comment by yaoshanliang** [comment]
@noringname Thanks for your interest in our dataset. Achelous is already released at [https://github.com/GuanRunwei/Achelous](https://github.com/GuanRunwei/Achelous). We will release the fusion-based YOLOv8 and YOLOX once our dataset is accepted.

**Comment by Sissuire** [comment]
Very nice work! I'm highly expected to see the source code and pretrained weights of YOLOX/YOOv8 and any other model presented in the work for a fair comparison and easy usage. @yaoshanliang

**Comment by yaoshanliang** [comment]
@Sissuire Thanks for your interest in our WaterScenes. Our open-sourced projects are in [https://github.com/GuanRunwei/Achelous](https://github.com/GuanRunwei/Achelous), [https://github.com/GuanRunwei/ASY-VRNet](https://github.com/GuanRunwei/ASY-VRNet), [https://github.com/GuanRunwei/Mask-VRDet-Official](https://github.com/GuanRunwei/Mask-VRDet-Official). If you have any questions in using the code, please do not hesitate to propose issues.
