### ISSUE TITLE
Sequence information for images

### ISSUE THREAD

**Issue by darrenjkt** [WaterScenes/WaterScenes#12]
Hi, thanks for your dataset. 

I was wondering if you have the sequence and sequence order for the images? So we can e.g. play it back as a video?

**Comment by yaoshanliang** [comment]
> Hi, thanks for your dataset.
> 
> I was wondering if you have the sequence and sequence order for the images? So we can e.g. play it back as a video?

Thanks for your interest in our WaterScenes. WaterScenes are key frames extracted from video sequences. Videos containing all frames will be published in our next project.
