### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by Byte247** [WaterScenes/WaterScenes#13]
Hello,

I can not seem to find a download link for the dataset? Where can I download it?

**Comment by yaoshanliang** [comment]
> Hello,
> 
> I can not seem to find a download link for the dataset? Where can I download it?

Thank you for your interest in our dataset. The download links are on this rep and I put them here [Baidu](https://pan.baidu.com/s/1mfYKFh9jJOdpYgs2nTe2Qg?pwd=data),[Google](https://drive.google.com/drive/u/2/folders/1ts_Jl91FlhliurzIOxx6DP2qChCGLDBj), [Google](https://drive.google.com/drive/folders/1SIwevcFfHXDIqlPcJEidAkAQ8AC-mW7g)
