### ISSUE TITLE
Dataset release date

### ISSUE THREAD

**Issue by Toytiny** [WaterScenes/WaterScenes#2]
Hi, 

Awesome dataset! We are very interested in your work and would like to use your dataset as soon as possible to facilitate our research. May I ask when this dataset will be released to the public? An approximate time would be greatly appreciated.

**Comment by yaoshanliang** [comment]
@Toytiny Thanks for your interest in our WaterScenes. We have released sample data and a toolkit in this repository for basic research on our dataset. The full dataset will be released once our work is accepted.
