### ISSUE TITLE
Calibration parameters and method

### ISSUE THREAD

**Issue by adithyab94** [WaterScenes/WaterScenes#4]
Hi,

Thanks for this wonderful work. If possible, Can you please tell me about the radar and camera calibration method you used for sensor fusion. It would be very helpful. I couldn't find about it on the paper either. Thank you

**Comment by yaoshanliang** [comment]
Thank you for your interest on our dataset.
We designed a novel radar-camera calibration board and method before data collection. It is another work and will be published. 
For the relationship between radar and camera, we provide the calibration parameters (text files) along with camera images and radar points. In addition, each point on the camera plane is already transformed with columns named `u` and `v` in radar files.

**Comment by adithyab94** [comment]
Great. Thank you
