### ISSUE TITLE
能否公开或共享数据集？

### ISSUE THREAD

**Issue by youlikesoilove** [WaterScenes/WaterScenes#5]
您好？请问公开数据的进度如何了？能够私下共享数据集？我也是做相关课题的，如果有可能的话，可以私下交流吗？

**Comment by yaoshanliang** [comment]
@youlikesoilove Thanks for your interest in our dataset. We welcome researchers to explore the field of autonomous driving on water surfaces. Please contact me via email: shanliang.yao@liverpool.ac.uk
