### ISSUE TITLE
rcs

### ISSUE THREAD

**Issue by Perry0817** [WaterScenes/WaterScenes#7]

**Comment by Perry0817** [comment]
Should there be data for rcs in the radar dataset, it is not found in the dataset you posted

**Comment by yaoshanliang** [comment]
> Should there be data for rcs in the radar dataset, it is not found in the dataset you posted

It show be `power` column in WaterScenes, as described in the readme file.

**Comment by Perry0817** [comment]
ok, i find it, thanks a lot
