### ISSUE TITLE
An issue about radar point cloud

### ISSUE THREAD

**Issue by CSPaulia** [WaterScenes/WaterScenes#9]
Hello dear developer. I encountered an issue when I was processing the data in 'radar_5_frames' directory. I found that some data was without 'comp_height' data. The 'comp_height' column is empty, such as '35341.csv'. So How can I solve this problem? Can I replace them with 0?

**Comment by yaoshanliang** [comment]
@CSPaulia Thank you for your feedback. We updated the data in 'radar_5_frames' directory with all 'comp_height' values. Please redownload the data from the original link.
